using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;


public class SC_BTCHARX : MonoBehaviour
{
    public SOSPECHOSO[] SOSPECHOSOX;
    public int IDBOTON;
    public Image IMGBOTON;
    // Start is called before the first frame update
    void Start()
    {
        SOSPECHOSOX[0] = SOSPECHOSOX[IDBOTON];
        IMGBOTON.sprite = SOSPECHOSOX[IDBOTON].SOSPECHOSOHUD;
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    public void BTPUSHA()
    {
        SC__CONTROLADOR.INSTANCE.ID = 0;

        SC__CONTROLADOR.INSTANCE.CHARHUD.sprite = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].SOSPECHOSOHUD;
        SC__CONTROLADOR.INSTANCE.CHAR.sprite = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].CHARNEUTRAL;
        SC__CONTROLADOR.INSTANCE.CHARFACE1.sprite = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].FACE1;
        SC__CONTROLADOR.INSTANCE.CHARFACE2.sprite = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].FACE2;
        SC__CONTROLADOR.INSTANCE.CHARFACE3.sprite = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].FACE3;

        SC__CONTROLADOR.INSTANCE.HOJAHUD.sprite = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].SOSPECHOSOHOJA;
        SC__CONTROLADOR.INSTANCE.TXNOMBRE.text = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].NOMBREDELSOSPECHOSO;
        SC__CONTROLADOR.INSTANCE.TXPROFESION.text = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].PROFESIONDELSOSPECHOSO;
    }
    public void BTPUSHB()
    {
        SC__CONTROLADOR.INSTANCE.ID = 1;

        SC__CONTROLADOR.INSTANCE.CHARHUD.sprite = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].SOSPECHOSOHUD;
        SC__CONTROLADOR.INSTANCE.CHAR.sprite = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].CHARNEUTRAL;
        SC__CONTROLADOR.INSTANCE.CHARFACE1.sprite = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].FACE1;
        SC__CONTROLADOR.INSTANCE.CHARFACE2.sprite = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].FACE2;
        SC__CONTROLADOR.INSTANCE.CHARFACE3.sprite = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].FACE3;

        SC__CONTROLADOR.INSTANCE.HOJAHUD.sprite = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].SOSPECHOSOHOJA;
        SC__CONTROLADOR.INSTANCE.TXNOMBRE.text = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].NOMBREDELSOSPECHOSO;
        SC__CONTROLADOR.INSTANCE.TXPROFESION.text = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].PROFESIONDELSOSPECHOSO;
    }
    public void BTPUSHC()
    {
        SC__CONTROLADOR.INSTANCE.ID = 2;

        SC__CONTROLADOR.INSTANCE.CHARHUD.sprite = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].SOSPECHOSOHUD;
        SC__CONTROLADOR.INSTANCE.CHAR.sprite = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].CHARNEUTRAL;
        SC__CONTROLADOR.INSTANCE.CHARFACE1.sprite = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].FACE1;
        SC__CONTROLADOR.INSTANCE.CHARFACE2.sprite = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].FACE2;
        SC__CONTROLADOR.INSTANCE.CHARFACE3.sprite = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].FACE3;

        SC__CONTROLADOR.INSTANCE.HOJAHUD.sprite = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].SOSPECHOSOHOJA;
        SC__CONTROLADOR.INSTANCE.TXNOMBRE.text = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].NOMBREDELSOSPECHOSO;
        SC__CONTROLADOR.INSTANCE.TXPROFESION.text = SOSPECHOSOX[SC__CONTROLADOR.INSTANCE.ID].PROFESIONDELSOSPECHOSO;
    }
}
